NAS:
  hosts:
    radiant-garden:
      ansible_host: "{{ radiant_garden.host }}"
      ansible_ssh_user: "{{ radiant_garden.user }}"
      ansible_ssh_pass: "{{ radiant_garden.password }}"
      ansible_connection: ssh
